# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_mmeAd5p-MVP_Ti9x69UZzUKeON2twLm
"""

import random
def generaterandom():
  return random.randrange(1,100)
def compare(num,guess):
  if abs(guess - num) >= 10:
    return "cold"
  elif guess == num:
    return "right"
  else:
    return "hot"
def main():
  randnum = generaterandom()
  while True:
    user=int(input("enter a num between 1 to 100  "))
    final=compare(randnum,user)
    if final == "right":
      print("you guessed right")
      break
    else:
      print(final)
main()